### PR TITLE
.github/workflows/sphinx: Further fix branch names with '/' in them

### PR DESCRIPTION
**Pull request by rkdarst**
- Encode a '/' as a '--' in the directory name.
- This isn't perfect (fails if there is already a double-dash), but
  better than before and good enough for now.
- Several other minor changes included.

### CODE REVIEW

**Comment by rkdarst** [comment]
This doesn't work yet, because it is in a detached head state in the action, and `git rev-parse --abbrev-ref HEAD` returns just HEAD and not the branch name.  But this was already broken.

**Comment by bast** [comment]
Is this now ready to go?

**Comment by rkdarst** [comment]
I *think* this works now: https://coderefinery.github.io/sphinx-lesson-template/branch/rkdarst--branch-name-slash-test/
I'm not entirely sure about deleting old branches, but I will see about that later... do you want to give it a look-over?

**Comment by bast** [comment]
Looks great! I will merge and do an iteration?

**Review by bast — APPROVED** [review]

**Pull request merged**
